pipeline {
    agent none
    environment {
        SERVER_CREDENTIALS = 's3-access'
        WEBHOOK_URL = credentials('DiscordWebhookDT')
        BUCKET = 'dmytro-team-bucket'
        REGION = 'eu-central-1'
    }
    stages {
        stage('Build') {
            agent { label 'java && jdk' }
            steps {
                git branch: 'dev', url: 'https://github.com/ProvedCode/backend.git'
                sh '''
                    chmod 744 ./mvnw
                    ./mvnw clean package
                    mv ./target/provedcode*.jar ./provedcode.jar
                    tar -cvzf provedcode-${BUILD_NUMBER}.tar.gz ./provedcode.jar
                '''
                withAWS(credentials: '${SERVER_CREDENTIALS}', region: '${REGION}') {
                    s3Upload(file: 'provedcode-${BUILD_NUMBER}.tar.gz', bucket: '${BUCKET}', path:'backend/')
                }
            }
        }
        stage('Deploy') {
            agent { label 'java && target && Team-Dmytro' }
            steps {
                withAWS(credentials: '${SERVER_CREDENTIALS}', region: '${REGION}') {
                    s3Download(file:'provedcode-${BUILD_NUMBER}.tar.gz', bucket:'${BUCKET}', path:'backend/')
                }
                sh '''
                    sudo systemctl stop provedcode || true
                    chmod 755 ./backend/install-systemd-service.sh
                    ./backend/install-systemd-service.sh
                    tar xpvf provedcode-${BUILD_NUMBER}.tar.gz
                    mv -f ./provedcode.jar ~/provedcode.jar
                    chmod 755 ~/provedcode.jar
                    rm provedcode-${BUILD_NUMBER}.tar.gz
                    sudo systemctl start provedcode
                '''
            }
        }
    }
    post {
        always {
            discordSend description: "Jenkins pipeline build: ${currentBuild.currentResult}",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                title: JOB_NAME,
                webhookURL: "${env.WEBHOOK_URL}"
            echo "${env.WEBHOOK_URL}"
        }
    }
}
